//! Specta type documentation and serialization notes.
//!
//! This module documents type serialization conventions used across the
//! TypeScript bindings generated by Specta.
//!
//! ## chrono::NaiveDate
//! With the `chrono` feature enabled on `sqlx` and the `serde` feature on `chrono`,
//! `NaiveDate` serializes to ISO string format `"YYYY-MM-DD"`.
//! Use `#[specta(type = String)]` on `NaiveDate` fields to instruct Specta
//! to represent them as `string` in the generated TypeScript bindings.
