//! VaultCompass Backend
//!
//! This crate provides the backend logic for managing financial portfolios,
//! including assets, accounts, and exchange rates.

#![deny(missing_docs)]
#![cfg_attr(not(test), deny(clippy::unwrap_used))]
#![cfg_attr(not(test), deny(clippy::panic))]
#![cfg_attr(not(test), deny(clippy::indexing_slicing))]
#![cfg_attr(not(test), deny(clippy::unreachable))]
#![cfg_attr(not(test), deny(clippy::todo))]
#![cfg_attr(not(test), deny(clippy::unimplemented))]

use crate::context::account::{
    AccountService, SqliteAccountRepository, SqliteHoldingRepository, SqliteTransactionRepository,
};
use crate::context::asset::{
    AssetService, SqliteAssetCategoryRepository, SqliteAssetPriceRepository, SqliteAssetRepository,
};
use crate::core::event_bus::Event;
use crate::core::{
    create_specta_builder, Database, SideEffectEventBus, SqlxTransactionManager, BACKEND,
};
use crate::use_cases::account_deletion::AccountDeletionUseCase;
use crate::use_cases::account_details::AccountDetailsUseCase;
use crate::use_cases::archive_asset::ArchiveAssetUseCase;
use crate::use_cases::asset_web_lookup::{AssetWebLookupUseCase, ReqwestOpenFigiClient};
use crate::use_cases::delete_asset::DeleteAssetUseCase;
use crate::use_cases::update_checker::UpdateState;
use anyhow::Context;
use std::{fs, path::PathBuf, sync::Arc};
use tauri::{Emitter, Manager};
use tauri_specta::Event as _;
use tracing_subscriber::{fmt, prelude::*, EnvFilter};

/// DDD Bounded Contexts
pub mod context;
/// Shared core utilities
pub mod core;
/// Application use cases
pub mod use_cases;

/// Global application state.
pub struct AppState {
    /// Database connection pool.
    pub db: Arc<core::Database>,
    /// System-wide event bus.
    pub event_bus: Arc<SideEffectEventBus>,
    /// Unified asset management service.
    pub asset_service: Arc<AssetService>,
    /// Account management service (owns account, holding, and transaction operations).
    pub account_service: Arc<AccountService>,
    /// Transaction manager for future cross-aggregate atomic writes (UoW pattern).
    pub transaction_manager: Arc<SqlxTransactionManager>,
}

/// Update lifecycle state — managed separately so it is accessible without a DB.
pub(crate) type ManagedUpdateState = Arc<UpdateState>;

/// Entry point for the Tauri application.
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let builder = create_specta_builder();

    #[cfg(debug_assertions)]
    builder
        .export(
            specta_typescript::Typescript::default()
                .bigint(specta_typescript::BigIntExportBehavior::Number)
                .header("// @ts-nocheck\n/* eslint-disable */\n// Generated by Specta - do not edit manually\n"),
            "../src/bindings.ts",
        )
        .expect("Failed to export typescript bindings");

    let invoke_handler = builder.invoke_handler();

    tauri::Builder::default()
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(
            tauri_plugin_window_state::Builder::default()
                .with_state_flags(
                    tauri_plugin_window_state::StateFlags::SIZE
                        | tauri_plugin_window_state::StateFlags::MAXIMIZED
                        | tauri_plugin_window_state::StateFlags::VISIBLE
                        | tauri_plugin_window_state::StateFlags::DECORATIONS
                        | tauri_plugin_window_state::StateFlags::FULLSCREEN,
                )
                .build(),
        )
        .plugin(tauri_plugin_opener::init())
        .setup(move |app| {
            let app_handle = app.handle().clone();

            builder.mount_events(&app_handle);

            let dirs = create_app_dirs(&app_handle)?;
            initialize_tracing(&dirs.log_dir)?;
            tracing::info!(target: BACKEND, "Initializing application backend");
            tracing::trace!(target: BACKEND, data_dir = ?dirs.local_data_dir, log_dir = ?dirs.log_dir, "Application directories");

            // Manage update state before DB init so it is available even on migration failure (R10, R18)
            app_handle.manage(Arc::new(UpdateState::new()) as ManagedUpdateState);

            tauri::async_runtime::block_on(async move {
                // R18 — emit migration error and keep app running so frontend can show error screen
                let db = match Database::new(dirs.local_data_dir).await {
                    Ok(db) => Arc::new(db),
                    Err(e) => {
                        tracing::error!(target: BACKEND, error = %e, "Database initialization failed (R18)");
                        let _ = app_handle.emit("db:migration_error", e.to_string());
                        return;
                    }
                };
                tracing::info!(target: BACKEND, "Database initialized successfully");

                let event_bus = Arc::new(SideEffectEventBus::new());

                // Spawn event forwarder
                let mut rx = event_bus.subscribe();
                let forwarder_handle = app_handle.clone();
                tauri::async_runtime::spawn(async move {
                    loop {
                        if rx.changed().await.is_err() {
                            break;
                        }
                        let event = rx.borrow().clone();
                        let _ = Event::emit(&event, &forwarder_handle);
                    }
                });

                let asset_repo = SqliteAssetRepository::new(db.pool.clone());
                let category_repo = SqliteAssetCategoryRepository::new(db.pool.clone());
                let price_repo = SqliteAssetPriceRepository::new(db.pool.clone());

                let asset_service = Arc::new(
                    AssetService::new(
                        Box::new(asset_repo),
                        Box::new(category_repo),
                        Box::new(price_repo),
                    )
                    .with_event_bus(event_bus.clone()),
                );

                let account_repo = SqliteAccountRepository::new(db.pool.clone());
                let holding_repo_for_svc = SqliteHoldingRepository::new(db.pool.clone());
                let transaction_repo_for_svc = SqliteTransactionRepository::new(db.pool.clone());
                let account_service = Arc::new(
                    AccountService::new(
                        Box::new(account_repo),
                        Box::new(holding_repo_for_svc),
                        Box::new(transaction_repo_for_svc),
                    )
                    .with_event_bus(event_bus.clone()),
                );

                let account_details_uc = AccountDetailsUseCase::new(
                    Arc::clone(&account_service),
                    Arc::clone(&asset_service),
                );

                let archive_asset_uc = ArchiveAssetUseCase::new(
                    Arc::clone(&account_service),
                    Arc::clone(&asset_service),
                );

                let delete_asset_uc = DeleteAssetUseCase::new(
                    Arc::clone(&account_service),
                    Arc::clone(&asset_service),
                );

                let account_deletion_uc =
                    AccountDeletionUseCase::new(Arc::clone(&account_service));

                app_handle.manage(account_details_uc);
                app_handle.manage(archive_asset_uc);
                app_handle.manage(delete_asset_uc);
                app_handle.manage(account_deletion_uc);

                app_handle.manage(AssetWebLookupUseCase::new(Arc::new(ReqwestOpenFigiClient::new())));

                let transaction_manager =
                    Arc::new(SqlxTransactionManager::new(db.pool.clone()));

                app_handle.manage(AppState {
                    db,
                    event_bus,
                    asset_service,
                    account_service,
                    transaction_manager,
                });

                tracing::info!(target: BACKEND, "Application backend initialized successfully");
            });

            Ok(())
        })
        .invoke_handler(invoke_handler)
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}

/// Application directory paths resolved at startup.
#[derive(Debug, Clone)]
struct AppDirectories {
    /// Path to the app-scoped local data directory (database location).
    local_data_dir: PathBuf,
    /// Path to the app-scoped log directory (log file location).
    log_dir: PathBuf,
}

fn create_app_dirs(app: &tauri::AppHandle) -> anyhow::Result<AppDirectories> {
    let path_resolver = app.path();

    let local_data_dir = path_resolver
        .app_local_data_dir()
        .with_context(|| "Failed to get app local data directory")?;
    fs::create_dir_all(&local_data_dir).with_context(|| "Failed to create data directory")?;

    let log_dir = path_resolver
        .app_log_dir()
        .with_context(|| "Failed to get app log directory")?;
    fs::create_dir_all(&log_dir).with_context(|| "Failed to create log directory")?;

    Ok(AppDirectories {
        local_data_dir,
        log_dir,
    })
}

/// Initialize tracing with dual output: append to `app.log` and write to stderr.
fn initialize_tracing(log_dir: &std::path::Path) -> anyhow::Result<()> {
    let log_file = log_dir.join("app.log");

    let file = fs::OpenOptions::new()
        .create(true)
        .append(true)
        .open(&log_file)
        .with_context(|| "Failed to open log file")?;

    tracing_subscriber::registry()
        .with(fmt::layer().with_ansi(false).with_writer(file))
        .with(fmt::layer().with_writer(std::io::stderr))
        .with(EnvFilter::try_from_default_env().unwrap_or_else(|_| EnvFilter::new("debug")))
        .init();

    tracing::trace!(target: BACKEND, "Logging initialized. Log file: {}", log_file.display());
    Ok(())
}
