// @ts-nocheck
/* eslint-disable */
// Generated by Specta - do not edit manually

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetches all active (non-archived) assets.
 */
async getAssets() : Promise<Result<Asset[], AssetApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches all assets including archived ones.
 */
async getAssetsWithArchived() : Promise<Result<Asset[], AssetApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets_with_archived") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new asset.
 */
async addAsset(dto: CreateAssetDTO) : Promise<Result<Asset, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_asset", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing asset.
 */
async updateAsset(dto: UpdateAssetDTO) : Promise<Result<Asset, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_asset", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unarchives an asset (R18).
 */
async unarchiveAsset(id: string) : Promise<Result<null, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Blocks automated price fetches for an asset (the lock — MKT-156, ADR-014).
 */
async blockAssetPriceRefresh(id: string) : Promise<Result<null, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("block_asset_price_refresh", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-allows automated price fetches for an asset (MKT-156).
 */
async unblockAssetPriceRefresh(id: string) : Promise<Result<null, AssetCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unblock_asset_price_refresh", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the canonical curated set of supported trading venues (AST-021).
 * Infallible — backed by an in-binary constant.
 */
async getSupportedExchanges() : Promise<Exchange[]> {
    return await TAURI_INVOKE("get_supported_exchanges");
},
/**
 * Fetches all active categories.
 * 
 * Read-only — only infrastructure failures can fire here, so the surface is
 * the narrow `CategoryApplicationError` (only `DatabaseError` is reachable).
 */
async getCategories() : Promise<Result<AssetCategory[], CategoryApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new category.
 * 
 * Returns the typed `CategoryCrudError` directly — no boundary type or mapper
 * is needed because every leaf in the composite (`CategoryApplicationError`,
 * `CategoryDomainError`) already serializes with `#[serde(tag = "code")]`,
 * and `CategoryCrudError`'s `#[serde(untagged)]` flattens them into a single
 * FE-visible union.
 */
async addCategory(label: string) : Promise<Result<AssetCategory, CategoryCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_category", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing category.
 */
async updateCategory(id: string, label: string) : Promise<Result<AssetCategory, CategoryCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { id, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a category.
 */
async deleteCategory(id: string) : Promise<Result<null, CategoryCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records (or overwrites) a market price for an asset on a given date (MKT-024/025).
 * price is a human-readable decimal; the backend converts to i64 micros at this boundary (MKT-024).
 */
async recordAssetPrice(assetId: string, date: string, price: number) : Promise<Result<null, AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_asset_price", { assetId, date, price }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all recorded prices for the given asset, sorted date descending (MKT-072).
 */
async getAssetPrices(assetId: string) : Promise<Result<AssetPrice[], AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_asset_prices", { assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates the date and/or price of an existing price record (MKT-083/084).
 */
async updateAssetPrice(assetId: string, originalDate: string, newDate: string, newPrice: number) : Promise<Result<null, AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_asset_price", { assetId, originalDate, newDate, newPrice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a specific price record by (asset_id, date) (MKT-090).
 */
async deleteAssetPrice(assetId: string, date: string) : Promise<Result<null, AssetPriceError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_asset_price", { assetId, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all accounts.
 */
async getAccounts() : Promise<Result<Account[], AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new account.
 */
async addAccount(dto: CreateAccountDTO) : Promise<Result<Account, AccountCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing account.
 */
async updateAccount(dto: UpdateAccountDTO) : Promise<Result<Account, AccountCrudError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_account", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an account (R5 — cascades to its holdings at the repo level).
 */
async deleteAccount(id: string) : Promise<Result<null, AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the distinct asset IDs that have transactions for the given account (TXL-013).
 */
async getAssetIdsForAccount(accountId: string) : Promise<Result<string[], AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_asset_ids_for_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all transactions for an account/asset pair (TRX-036).
 */
async getTransactions(accountId: string, assetId: string) : Promise<Result<Transaction[], AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transactions", { accountId, assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Declares a currency pair (FXR-054). Idempotent: returns the existing pair
 * rather than duplicating it.
 */
async declareCurrencyPair(fromCurrency: string, toCurrency: string) : Promise<Result<CurrencyPair, CurrencyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("declare_currency_pair", { fromCurrency, toCurrency }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a rate for a pair (FXR-025). Converts `rate: f64` to i64 micros
 * at the IPC boundary (FXR-024). Sets `source = Manual` (FXR-101).
 * Ensures the pair exists as a side-effect (FXR-013).
 */
async recordCurrencyRate(fromCurrency: string, toCurrency: string, date: string, rate: number) : Promise<Result<CurrencyRate, CurrencyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_currency_rate", { fromCurrency, toCurrency, date, rate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing rate (FXR-052). Same-date = in-place overwrite;
 * changed-date = delete-old + upsert-new. Returns `RateNotFound` when the
 * original record does not exist.
 */
async updateCurrencyRate(fromCurrency: string, toCurrency: string, originalDate: string, newDate: string, newRate: number) : Promise<Result<null, CurrencyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_currency_rate", { fromCurrency, toCurrency, originalDate, newDate, newRate }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes the rate at `(from_currency, to_currency, date)` (FXR-053).
 * Returns `RateNotFound` when absent; never removes the pair (FXR-014).
 */
async deleteCurrencyRate(fromCurrency: string, toCurrency: string, date: string) : Promise<Result<null, CurrencyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_currency_rate", { fromCurrency, toCurrency, date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all pairs enriched with their most-recent rate (FXR-051).
 */
async getCurrencyPairs() : Promise<Result<CurrencyPairSummary[], CurrencyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_currency_pairs") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns all rates for the given pair ordered by date descending (FXR-050).
 * Returns an empty list for an unknown pair — never `RateNotFound`.
 */
async getCurrencyRates(fromCurrency: string, toCurrency: string) : Promise<Result<CurrencyRate[], CurrencyError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_currency_rates", { fromCurrency, toCurrency }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Lists every supported provider with its `has_key` / `active_tier` (KEY-016).
 */
async getProviderConnections() : Promise<Result<ProviderConnection[], ConnectionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_provider_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Persists a provider key via the tier ladder (KEY-010/011/012). Returns the
 * resulting `ProviderConnection` so the FE learns the `active_tier`.
 */
async saveProviderKey(args: SaveProviderKeyArgs) : Promise<Result<ProviderConnection, ConnectionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_provider_key", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Probes a provider with the supplied candidate key (KEY-021/022). The three
 * outcomes are successful returns, not errors (KEY-023).
 */
async testProviderKey(args: TestProviderKeyArgs) : Promise<Result<ProviderKeyTestOutcome, ConnectionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_provider_key", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clears a provider's key from every tier (KEY-013). Idempotent.
 */
async removeProviderKey(args: RemoveProviderKeyArgs) : Promise<Result<null, ConnectionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_provider_key", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Archives an asset, guarded against active holdings (OQ-6).
 */
async archiveAsset(id: string) : Promise<Result<null, ArchiveAssetError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an asset, guarded against existing transactions.
 */
async deleteAsset(id: string) : Promise<Result<null, DeleteAssetError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Seeds a holding directly from a known quantity and total cost (TRX-042, TRX-047).
 */
async openHolding(dto: OpenHoldingDTO) : Promise<Result<Transaction, OpenHoldingError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_holding", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a purchase of an asset into an account (TRX-027).
 */
async buyHolding(dto: BuyHoldingDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("buy_holding", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a sale of an asset from an account (SEL-012, SEL-021, SEL-023, SEL-024).
 */
async sellHolding(dto: SellHoldingDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sell_holding", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Corrects an existing transaction and recalculates the affected holding (TRX-031).
 */
async correctTransaction(id: string, accountId: string, dto: CorrectTransactionDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("correct_transaction", { id, accountId, dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancels a transaction and recalculates (or removes) the associated holding (TRX-034).
 */
async cancelTransaction(id: string, accountId: string) : Promise<Result<null, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_transaction", { id, accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a cash deposit into an account (CSH-022).
 */
async recordDeposit(dto: DepositDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_deposit", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a cash withdrawal from an account (CSH-032).
 */
async recordWithdrawal(dto: WithdrawalDTO) : Promise<Result<Transaction, HoldingTransactionError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_withdrawal", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a cash dividend attributed to a held asset (DIV-023).
 */
async recordDividend(dto: DividendDTO) : Promise<Result<Transaction, DividendError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_dividend", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Records a zero-cost free-share distribution attributed to a held asset (FSD-022).
 */
async recordFreeShares(dto: FreeSharesDTO) : Promise<Result<Transaction, FreeSharesError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_free_shares", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the full account details view for the given account (ACD-012 to ACD-041).
 */
async getAccountDetails(accountId: string) : Promise<Result<AccountDetailsResponse, AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_details", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns one `AccountSummary` per non-deleted account (ACC-021).
 */
async getAccountSummaries() : Promise<Result<AccountSummary[], AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_summaries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns per-period performance figures for a single account (PRF spec).
 */
async getAccountPerformance(accountId: string) : Promise<Result<AccountPerformanceResponse, AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_performance", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the number of active holdings and transactions for an account (ACC-020).
 * 
 * Used by the frontend to decide whether to show the standard or reinforced
 * delete confirmation dialog (ACC-018 vs ACC-019).
 */
async getAccountDeletionSummary(accountId: string) : Promise<Result<AccountDeletionSummary, AccountApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_deletion_summary", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Searches OpenFIGI for instruments matching `query` along the explicit `mode`
 * path (WEB-014, WEB-020). Returns up to 30 results (WEB-022).
 * 
 * The frontend chooses the path: `Isin` validates the query against ISO 6166
 * (WEB-016) before any HTTP call and routes to `/v3/mapping`; `Keyword`
 * normalizes diacritics (WEB-015) and routes to `/v3/search`. HTTP 429
 * surfaces as `RateLimited`; every other reachability failure surfaces as
 * `NetworkError`; ISIN format failures surface as `InvalidIsinFormat` (WEB-025).
 */
async lookupAsset(query: string, mode: LookupMode) : Promise<Result<AssetLookupResult[], WebLookupApplicationError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("lookup_asset", { query, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatches an all-accounts auto-fetch task (MKT-122, MKT-130).
 * Returns `Ok(())` immediately after successful dispatch; per-asset results
 * arrive asynchronously via `AssetPriceUpdated` events (MKT-112).
 */
async fetchAllAssetPrices() : Promise<Result<null, FetchAllAssetPricesError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_all_asset_prices") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dispatches a per-account price-fetch task (MKT-132, MKT-131).
 * Returns `Ok(())` immediately after successful dispatch.
 */
async fetchAccountAssetPrices(accountId: string) : Promise<Result<null, FetchAccountAssetPricesError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fetch_account_asset_prices", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks whether a new application version is available (R1, R25).
 * 
 * Returns `None` if the application is up to date or if the check fails due
 * to network or server errors (R21). Emits `"update:available"` on the app
 * handle if an update is found.
 */
async checkForUpdate() : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts downloading the available update in the background (R6).
 * 
 * Returns immediately — the download runs as a detached async task.
 * Progress is reported via `"update:progress"` events (R8).
 * On success, emits `"update:complete"` (R11).
 * On failure, emits `"update:error"` (R23).
 * Concurrent download requests are silently ignored (R10).
 */
async downloadUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Installs the downloaded update and restarts the application (R13).
 * 
 * Must be called after `download_update` has completed successfully.
 * Returns an error if no downloaded update is available.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command allowing the frontend to emit structured log entries
 * into the backend tracing system (visible in app logs and collect-logs output).
 */
async logFrontend(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { level, message });
}
}

/** user-defined events **/


export const events = __makeEvents__<{
event: Event
}>({
event: "event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Represents a financial account — the Aggregate Root of the Account bounded context.
 * Owns all holdings and transactions for this account.
 * 
 * The `holdings`, `transactions`, and `pending_changes` fields are populated only
 * when the aggregate is loaded for mutation via `AccountRepository::get_with_holdings_and_transactions`.
 * They are excluded from Tauri serialization and TypeScript bindings.
 */
export type Account = { 
/**
 * Unique identifier (uuid).
 */
id: string; 
/**
 * User defined name.
 */
name: string; 
/**
 * ISO 4217 currency code for this account (TRX-021).
 */
currency: string; 
/**
 * How often this account is updated.
 */
update_frequency: UpdateFrequency }
/**
 * Application-layer errors raised by the Account bounded context.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "...", ... }` shape.
 */
export type AccountApplicationError = 
/**
 * No account exists with the requested ID.
 */
{ code: "AccountNotFound"; account_id: string } | 
/**
 * Account name (case-insensitive) collides with an existing one.
 */
{ code: "NameAlreadyExists" } | 
/**
 * Application-layer translation of any infrastructure failure from an
 * account-side repository call. Unit variant — no `hint` payload on the
 * wire; the full diagnostic chain is preserved server-side via
 * `tracing::error!` at the translation site. FE shows the i18n key
 * `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * Service-layer composite for the **Account CRUD** failure surface — the
 * write commands `add_account` and `update_account`.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer (this module) — raises
 * `NameAlreadyExists` and `DatabaseError`.
 * - `AccountDomainError` — domain layer (`account/domain/`) — raises
 * `NameEmpty` / `InvalidCurrency` from the `Account::new` /
 * `Account::with_id` constructors on their own input.
 */
export type AccountCrudError = 
/**
 * Service-layer rejection (`NameAlreadyExists`, `DatabaseError`).
 */
AccountApplicationError | 
/**
 * Aggregate-constructor rejection (`NameEmpty`, `InvalidCurrency`).
 */
AccountDomainError
/**
 * Pre-deletion counts for an account (ACC-020).
 */
export type AccountDeletionSummary = { 
/**
 * Number of active holdings (quantity > 0) in the account.
 */
holding_count: number; 
/**
 * Total number of transactions associated with the account.
 */
transaction_count: number }
/**
 * Top-level response for the get_account_details command (ACD spec).
 */
export type AccountDetailsResponse = { 
/**
 * Display name of the account (ACD-032).
 */
account_name: string; 
/**
 * Active holdings (quantity > 0), sorted by asset_name asc (ACD-020, ACD-033).
 */
holdings: HoldingDetail[]; 
/**
 * Closed positions (quantity == 0), sorted by asset_name asc (ACD-044, ACD-046).
 */
closed_holdings: ClosedHoldingDetail[]; 
/**
 * Total holding count regardless of quantity (ACD-034).
 */
total_holding_count: number; 
/**
 * Sum of cost_basis across all active holdings, 0 if none (ACD-031).
 */
total_cost_basis: number; 
/**
 * Sum of total_realized_pnl across ALL holdings (active + closed), 0 if none (ACD-047).
 */
total_realized_pnl: number; 
/**
 * Sum of unrealized_pnl across priced active holdings (foreign holdings converted to
 * account currency, FXR-040). None when none qualify (MKT-040).
 */
total_unrealized_pnl: number | null; 
/**
 * Total economic value of the account in account-currency micros (CSH-094):
 * `cash_holding.quantity + Σ_h (h.quantity × latest_price(h))` over non-cash active holdings.
 * Unpriced non-cash holdings contribute 0 (no fallback to `average_price`).
 * Returns 0 when no Cash Holding and no priced non-cash holdings.
 */
total_global_value: number; 
/**
 * Sum of dividend cash credited across all of the account's dividend transactions, in account
 * currency (i64 micros). 0 when none (DIV-073).
 */
total_dividends_received: number }
/**
 * Typed errors for the account bounded context.
 * 
 * All domain error enums in this module derive `serde::Serialize` + `specta::Type` +
 * `#[serde(tag = "code")]` so they can be exposed verbatim at the Tauri boundary.
 * Boundary error types compose them via untagged unions to avoid redefining variants
 * (review feedback on PR #5).
 */
export type AccountDomainError = 
/**
 * Account name is empty or whitespace-only. Raised by the `Account`
 * aggregate constructor on its own input — value-object validation,
 * domain-class per Rule B'.
 */
{ code: "NameEmpty" } | 
/**
 * The currency string is not a valid ISO 4217 code. Raised by the
 * `Account` aggregate constructor on its own input. Struct variant so the
 * internally-tagged serde representation (`#[serde(tag = "code")]`) can
 * flatten the offending currency alongside `code` at the FE boundary
 * (serde does not support internally-tagged tuple variants).
 */
{ code: "InvalidCurrency"; currency: string }
/**
 * Typed errors raised by Account aggregate operations (buy/sell/correct/cancel/cash).
 */
export type AccountOperationError = 
/**
 * Attempt to sell an asset with no open position (quantity = 0).
 */
{ code: "ClosedPosition" } | 
/**
 * Sell quantity exceeds the currently held units.
 */
{ code: "Oversell"; available: number; requested: number } | 
/**
 * Correcting a transaction would leave a later sell with insufficient units.
 */
{ code: "CascadingOversell" } | 
/**
 * No transaction with the given ID exists within this account.
 */
{ code: "TransactionNotFound" } | 
/**
 * Attempted cash debit (or chronological replay step) would drive the cash holding strictly negative (CSH-080).
 */
{ code: "InsufficientCash"; current_balance_micros: number; currency: string }
/**
 * Top-level response for `get_account_performance` — recomputed on read (ADR-013).
 */
export type AccountPerformanceResponse = { 
/**
 * Display name of the account.
 */
account_name: string; 
/**
 * ISO 4217 currency code of the account.
 */
currency: string; 
/**
 * True only for Automatic/ManualDay/ManualWeek (PRF-013).
 */
month_view_available: boolean; 
/**
 * One row per year, most-recent first (PRF-041). month is None for each row.
 */
yearly: PerformancePeriod[]; 
/**
 * One row per month over the full span, most-recent first.
 * Empty when month_view_available is false (PRF-013, PRF-015).
 */
monthly: PerformancePeriod[] }
/**
 * Row returned by `get_account_summaries` (ACC-021). Pairs each `Account` with its
 * computed `total_global_value` so the Accounts list can render the value column
 * without each row calling `get_account_details` separately.
 */
export type AccountSummary = { 
/**
 * Account identifier (UUID).
 */
id: string; 
/**
 * User-defined display name.
 */
name: string; 
/**
 * ISO 4217 currency code; matches `Account.currency`.
 */
currency: string; 
/**
 * Manual / Automatic update cadence (purely informational, ACC-004).
 */
update_frequency: UpdateFrequency; 
/**
 * Total economic value in account-currency micros (CSH-094 / FXR-041): cash
 * quantity plus the sum of `quantity × latest_price` over priced active non-cash
 * holdings, with foreign holdings converted to account currency. Unpriced holdings,
 * or foreign holdings with no usable rate (FXR-034), contribute 0.
 */
total_global_value: number }
/**
 * Application-layer rejection specific to the `archive_asset` use case —
 * the cross-BC active-holdings check performed by the orchestrator before
 * delegating to `AssetService::archive_asset`.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors): this
 * rejection is born at the orchestrator (it queries the account service and
 * decides whether to proceed), not by an aggregate method on its own loaded
 * state — application-class.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape through the
 * `ArchiveAssetError` untagged composite.
 */
export type ArchiveAssetApplicationError = 
/**
 * Asset still has non-zero holdings in at least one account (OQ-6).
 */
{ code: "ActiveHoldings" }
/**
 * Use-case composite for the **archive asset** failure surface — the single
 * command `archive_asset` (OQ-6) and its full chain of rejections.
 * 
 * Replaces the anyhow-era `ArchiveAssetCommandError` boundary type. This IS
 * the FE-facing contract for the `archive_asset` Tauri command — each leaf
 * already serializes with `#[serde(tag = "code")]`, and `#[serde(untagged)]`
 * here flattens them into a single FE-visible union.
 * 
 * Each leaf lives in its rightful layer:
 * - `AssetCrudError` — asset BC composite (`asset/application/`), carries
 * `AssetApplicationError::NotFound` and
 * `AssetDomainError::CashAssetNotEditable` propagated verbatim per the
 * composition-over-redefinition rule.
 * - `AccountApplicationError` — account BC (`account/application/`), surfaces
 * `DatabaseError` from the cross-BC active-holdings check.
 * - `ArchiveAssetApplicationError` — use-case-owned (this file), raises
 * `ActiveHoldings` from the orchestrator.
 */
export type ArchiveAssetError = 
/**
 * Asset BC rejection (`NotFound`, `CashAssetNotEditable`, propagated
 * `DatabaseError`).
 */
AssetCrudError | 
/**
 * Account BC rejection (`DatabaseError` from the cross-BC
 * active-holdings check).
 */
AccountApplicationError | 
/**
 * Use-case orchestration rejection (`ActiveHoldings`).
 */
ArchiveAssetApplicationError
/**
 * A financial instrument or resource held by a user.
 */
export type Asset = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * Display name.
 */
name: string; 
/**
 * Asset classification.
 */
class: AssetClass; 
/**
 * Category link.
 */
category: AssetCategory; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * Risk score from 1 to 5.
 */
risk_level: number; 
/**
 * Ticker / free-form reference (mandatory — R1). For quoted assets that
 * also carry an ISIN, the canonical ISO 6166 identity lives in `isin`
 * (AST-023); `reference` holds the provider-lookup symbol (Stooq, etc.).
 */
reference: string; 
/**
 * Optional ISIN (ISO 6166, 12 chars, Luhn-validated — AST-023). Stored
 * in the normalized uppercase form returned by `validate_isin`.
 */
isin: string | null; 
/**
 * Whether the asset is archived (soft-archived, reversible).
 */
is_archived: boolean; 
/**
 * Optional canonical trading venue (AST-021).
 */
exchange: Exchange | null; 
/**
 * When true, the asset is excluded from every price-fetch task scope
 * (MKT-150 / MKT-151, ADR-014), preserving its most recently recorded
 * price. Independent of `is_archived`; toggled only by the dedicated
 * `block_price_refresh` / `unblock_price_refresh` actions.
 */
price_refresh_blocked: boolean }
/**
 * Application-layer rejections for the Asset aggregate of the Asset BC —
 * concerns raised at the service layer rather than by an aggregate method on
 * its own loaded state.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `NotFound` is born when `asset_repo.get_by_id` returns `Ok(None)` — a
 * service-level translation, not an aggregate invariant. Carries the
 * requested ID for FE diagnostic surfacing.
 * - `DatabaseError` is the application-layer translation of any raw
 * infrastructure failure from an asset-repo call. The diagnostic chain is
 * preserved via `tracing::error!` at the same translation site; the
 * variant carries no payload (per the project-specific infra-translation
 * rule in `docs/plan/error-model-refactor.md`).
 */
export type AssetApplicationError = 
/**
 * No asset exists with the requested ID. Born at the service layer when
 * `asset_repo.get_by_id` returns `None`.
 */
{ code: "NotFound"; id: string } | 
/**
 * Application-layer translation of any infrastructure failure from an
 * asset-repo call. Unit variant — no `hint` payload on the wire; the full
 * diagnostic chain is preserved server-side via `tracing::error!` at the
 * translation site. FE shows the i18n key `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * A user-defined grouping for assets.
 */
export type AssetCategory = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * Display name.
 */
name: string }
/**
 * Represents the classification of an asset.
 */
export type AssetClass = 
/**
 * Real estate properties or REITs.
 */
"RealEstate" | 
/**
 * Fiat currency or highly liquid equivalents.
 */
"Cash" | 
/**
 * Individual company equities.
 */
"Stocks" | 
/**
 * Fixed income securities.
 */
"Bonds" | 
/**
 * Exchange Traded Funds.
 */
"ETF" | 
/**
 * Exchange Traded Products — umbrella class for ETF, ETN, and ETC
 * instruments that OpenFIGI returns under a single `"ETP"` securityType
 * (WEB-023). Used when the structural distinction isn't available; users
 * can edit the class manually if they need ETF/ETN/ETC granularity.
 */
"ETP" | 
/**
 * Managed investment funds.
 */
"MutualFunds" | 
/**
 * Cryptocurrencies or other blockchain-based assets.
 */
"DigitalAsset" | 
/**
 * Leveraged or contingent instruments derived from an underlying asset (warrants, options, futures, rights).
 */
"Derivatives"
/**
 * Service-layer composite for the Asset CRUD failure surface — the write
 * commands `add_asset`, `update_asset`, `unarchive_asset`, plus the
 * service-internal `archive_asset` / `delete_asset` consumed by use cases.
 * 
 * Composes three leaves: `AssetApplicationError` (NotFound, DatabaseError),
 * `AssetDomainError` (input validation + archive / cash / system-managed
 * invariants), `CategoryApplicationError` (cross-aggregate category lookup
 * in create/update).
 */
export type AssetCrudError = 
/**
 * Service-layer rejection (`NotFound`, `DatabaseError`).
 */
AssetApplicationError | 
/**
 * Aggregate-level domain rejection (input validation, archive / cash /
 * system-managed invariants on loaded state).
 */
AssetDomainError | 
/**
 * Category-side application rejection — surfaces `NotFound { id }` from the
 * cross-aggregate category lookup in `create_asset` / `update_asset`.
 */
CategoryApplicationError
/**
 * Typed errors for asset domain validation. Only aggregate-method or
 * value-object rejections live here per the rejection-layer rule
 * (`docs/ddd-reference.md` § Errors).
 * 
 * Tagged with `#[serde(tag = "code")]` for exposure through the
 * `AssetCrudError` untagged composite. Payload-bearing variants are
 * struct-shaped (internally-tagged serde rejects tuple variants).
 */
export type AssetDomainError = 
/**
 * Asset name is empty or whitespace-only.
 */
{ code: "NameEmpty" } | 
/**
 * Asset reference (ticker/ISIN) is empty or whitespace-only.
 */
{ code: "ReferenceEmpty" } | 
/**
 * Risk level is outside the 1–5 range.
 */
{ code: "InvalidRiskLevel"; received: number } | 
/**
 * The currency string is not a valid ISO 4217 code.
 */
{ code: "InvalidCurrency"; currency: string } | 
/**
 * The asset is archived and cannot be edited.
 */
{ code: "Archived" } | 
/**
 * The asset is a system Cash Asset and cannot be edited, archived, unarchived, or deleted (CSH-016).
 */
{ code: "CashAssetNotEditable" } | 
/**
 * The supplied exchange code is not a member of the canonical curated set (AST-001).
 */
{ code: "InvalidExchange"; exchange_code: string } | 
/**
 * The supplied ISIN fails the ISO 6166 format validation (AST-023, WEB-016).
 * Sub-variants of the `IsinFormatError` (wrong length, invalid charset, bad
 * check digit) collapse to this single wire code per the `isin.rs` doc.
 */
{ code: "InvalidIsinFormat" }
/**
 * Flat error enum for the asset bounded context (per error-model.md).
 * 
 * Holds every variant the asset BC can raise on the new fetch surface. The
 * existing `AssetApplicationError`, `AssetPriceApplicationError`, and the
 * legacy composites remain untouched on the existing CRUD / price-history
 * surfaces (see docs/techdebt.md for the planned retrofit).
 */
export type AssetError = 
/**
 * Application-layer translation of any infrastructure failure from an
 * asset-repo call on the fetch surface.
 */
{ code: "DatabaseError" }
/**
 * Transient value object returned by the orchestrator's `search` method.
 * Mirrors the shape exposed at the Tauri boundary.
 */
export type AssetLookupResult = { 
/**
 * Full instrument name (e.g. `"AIR LIQUIDE SA"`).
 */
name: string; 
/**
 * Ticker symbol returned by OpenFIGI; `None` when no ticker is available
 * (WEB-046). Consistent across both lookup paths so the FE always pre-fills
 * `Asset.reference` with a value market-data providers (Stooq, etc.) can
 * resolve.
 */
reference: string | null; 
/**
 * ISIN (ISO 6166, 12 chars normalized). Populated only on the ISIN path
 * with the validated query (WEB-046); `None` on the keyword path because
 * OpenFIGI's `/v3/search` response does not expose ISIN.
 */
isin: string | null; 
/**
 * ISO 4217 currency forwarded from OpenFIGI (WEB-024).
 */
currency: string | null; 
/**
 * Asset class derived from `securityType` (WEB-023).
 */
asset_class: AssetClass | null; 
/**
 * Canonical exchange resolved via WEB-049 mapper; absent when the venue
 * is not in the curated set.
 */
exchange: Exchange | null }
/**
 * A recorded market price for a financial asset on a specific date.
 * Owned by the `asset` bounded context (MKT spec).
 */
export type AssetPrice = { 
/**
 * ID of the asset whose market price this record describes.
 */
asset_id: string; 
/**
 * ISO 8601 calendar date of the price observation (e.g. "2026-04-26").
 */
date: string; 
/**
 * Market price per unit in the asset's native currency (i64 micro-units, ADR-001).
 */
price: number; 
/**
 * Provenance of this price record (MKT-100).
 */
source: AssetPriceSource }
/**
 * Application-layer rejections for the AssetPrice sub-aggregate of the Asset
 * BC — concerns raised at the service layer rather than by an aggregate method
 * on its own loaded state.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `PriceNotFound` is born when `price_repo.get_by_asset_and_date` returns
 * `Ok(None)` for an `(asset_id, date)` pair the service expected to exist
 * (update / delete) — a service-level translation, not an aggregate
 * invariant. Carries both keys for FE diagnostic surfacing.
 * - `DatabaseError` is the application-layer translation of any raw infra
 * failure from a price-repo call. The diagnostic chain is preserved via
 * `tracing::error!` at the same translation site; the variant carries no
 * payload (per the project-specific infra-translation rule in
 * `docs/plan/error-model-refactor.md`).
 */
export type AssetPriceApplicationError = 
/**
 * No price record exists for the given (asset_id, date) pair (MKT-083 / MKT-090).
 */
{ code: "PriceNotFound"; asset_id: string; date: string } | 
/**
 * The target asset is archived (AST-006). Mutating price commands
 * (record / update / delete) reject; reads remain allowed.
 */
{ code: "Archived" } | 
/**
 * Application-layer translation of any infrastructure failure from a
 * price-repo call. Unit variant — no `hint` payload on the wire; the full
 * diagnostic chain is preserved server-side via `tracing::error!` at the
 * translation site. FE shows the i18n key `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * Typed errors for asset price value-object validation. Only aggregate-method
 * or value-object rejections live here per the rejection-layer rule
 * (`docs/ddd-reference.md` § Errors); the "no record at this (asset_id, date)"
 * rejection is service-level and lives in `AssetPriceApplicationError`.
 * 
 * Tagged with `#[serde(tag = "code")]` for exposure through the
 * `AssetPriceError` untagged composite. Payload-bearing variants are
 * struct-shaped (internally-tagged serde rejects tuple variants).
 */
export type AssetPriceDomainError = 
/**
 * Price must be strictly positive.
 */
{ code: "NotPositive" } | 
/**
 * Price value is not a finite floating-point number.
 * Emitted by the service boundary before micro conversion; `AssetPrice::new()` never produces this.
 */
{ code: "NonFinite" } | 
/**
 * Price date is in the future.
 */
{ code: "DateInFuture" } | 
/**
 * The supplied date string is not parseable as ISO 8601 (`YYYY-MM-DD`).
 */
{ code: "InvalidDateFormat"; date: string }
/**
 * Service-layer composite for the **AssetPrice** failure surface — the write
 * commands `record_asset_price` / `update_asset_price` / `delete_asset_price`
 * and the read `get_asset_prices`.
 * 
 * Composes three leaves:
 * - `AssetApplicationError` — cross-aggregate asset-existence check
 * (`record_asset_price` and `get_asset_prices` reject when the asset row
 * itself is missing — MKT-043).
 * - `AssetPriceApplicationError` — price-row rejection (`PriceNotFound`,
 * `DatabaseError`).
 * - `AssetPriceDomainError` — value-object validation
 * (`NotPositive` / `NonFinite` / `DateInFuture` / `InvalidDateFormat`).
 */
export type AssetPriceError = 
/**
 * Asset-row rejection (`NotFound`, `DatabaseError`) from the
 * asset-existence check that gates write commands.
 */
AssetApplicationError | 
/**
 * Price-row rejection (`PriceNotFound`, `DatabaseError`).
 */
AssetPriceApplicationError | 
/**
 * Value-object validation (`NotPositive`, `NonFinite`, `DateInFuture`,
 * `InvalidDateFormat`).
 */
AssetPriceDomainError
/**
 * Provenance qualifier for an AssetPrice record (MKT-100).
 */
export type AssetPriceSource = 
/**
 * User-driven write: manual entry or price-history edit (MKT-101).
 */
"Manual" | 
/**
 * Auto-fetched from Stooq (MKT-102).
 */
"Stooq"
/**
 * Parameters for recording a purchase of an asset into an account.
 */
export type BuyHoldingDTO = { 
/**
 * Account where the purchase is recorded.
 */
account_id: string; 
/**
 * Financial asset being purchased.
 */
asset_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units.
 */
quantity: number; 
/**
 * Unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Application-layer rejections for the Category sub-aggregate of the Asset
 * bounded context — concerns raised at the service layer rather than by an
 * aggregate method on its own loaded state.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `NotFound` is born when `category_repo.get_by_id` returns `Ok(None)` —
 * a service-level translation, not an aggregate invariant.
 * - `DuplicateName` is born when the service-layer `find_by_name` uniqueness
 * pre-check matches an existing row — a cross-aggregate invariant.
 * - `DatabaseError` is the application-layer translation of any raw
 * infrastructure failure from a category-repo call. The diagnostic chain
 * is preserved via `tracing::error!` at the same translation site; the
 * variant carries no payload (per the project-specific infra-translation
 * rule in `docs/plan/error-model-refactor.md`).
 * 
 * Tagged with `#[serde(tag = "code")]` so each variant serializes as a flat
 * `{ code: "..." }` shape across the Tauri boundary. `NotFound` carries the
 * requested ID as a struct field so the FE can surface it diagnostically.
 */
export type CategoryApplicationError = 
/**
 * No category exists with the requested ID. Born at the service layer
 * when `category_repo.get_by_id` returns `None`.
 */
{ code: "NotFound"; id: string } | 
/**
 * A category with the same name (case-insensitive) already exists. Born
 * at the service layer from a `find_by_name` uniqueness pre-check before
 * the repository write — a cross-aggregate invariant, not a single-
 * aggregate state rule.
 */
{ code: "DuplicateName" } | 
/**
 * Application-layer translation of any infrastructure failure from a
 * category-repo call. Unit variant — no `hint` payload on the wire; the
 * full diagnostic chain is preserved server-side via `tracing::error!`
 * at the translation site. FE shows the i18n key `error.DatabaseError`.
 */
{ code: "DatabaseError" }
/**
 * Service-layer composite for the **Category CRUD** failure surface — the
 * write commands `add_category`, `update_category`, `delete_category`.
 * `get_categories` (read-only) returns the narrower `CategoryApplicationError`
 * directly because it has no domain-rejection paths.
 * 
 * Each leaf lives in its rightful layer:
 * - `CategoryApplicationError` — application layer (this module) — raises
 * `NotFound`, `DuplicateName`, `DatabaseError`.
 * - `CategoryDomainError` — domain layer (`asset/domain/`) — raises
 * `LabelEmpty` (value-object validation), `SystemReadonly` /
 * `SystemProtected` (aggregate-method invariants on loaded state).
 */
export type CategoryCrudError = 
/**
 * Service-layer rejection (`NotFound`, `DuplicateName`, `DatabaseError`).
 */
CategoryApplicationError | 
/**
 * Aggregate-level domain rejection (`LabelEmpty`, `SystemReadonly`,
 * `SystemProtected`).
 */
CategoryDomainError
/**
 * Typed errors for category domain validation.
 * 
 * Only genuine aggregate-method or value-object rejections live here per the
 * rejection-layer rule (`docs/ddd-reference.md` § Errors):
 * - `LabelEmpty` — value-object validation in `AssetCategory::new` /
 * `update_from`.
 * - `SystemReadonly` / `SystemProtected` — aggregate methods
 * `ensure_renameable` / `ensure_deletable` enforced on loaded state.
 * 
 * Tagged with `#[serde(tag = "code")]` so it can be exposed verbatim at the
 * Tauri boundary through the `CategoryCrudError` untagged composite.
 */
export type CategoryDomainError = 
/**
 * Category label is empty or whitespace-only.
 */
{ code: "LabelEmpty" } | 
/**
 * Attempt to rename the system default category.
 */
{ code: "SystemReadonly" } | 
/**
 * Attempt to delete the system default category.
 */
{ code: "SystemProtected" }
/**
 * Enriched view of a fully-closed position (quantity == 0, ACD-044).
 */
export type ClosedHoldingDetail = { 
/**
 * ID of the previously held asset.
 */
asset_id: string; 
/**
 * Display name of the asset.
 */
asset_name: string; 
/**
 * Ticker or user-defined reference.
 */
asset_reference: string; 
/**
 * Total realized P&L for this position (micro-units, ACD-045).
 */
realized_pnl: number; 
/**
 * ISO date of the most recent sell for this position ("YYYY-MM-DD", ACD-043).
 */
last_sold_date: string }
/**
 * Single flat error enum for the `connection` bounded context (gold error model).
 * 
 * `#[serde(tag = "code")]` makes each variant serialize as
 * `{ "code": "VariantName", ...payload }` on the wire. `KeyStoreError` is the
 * keychain-world analog of the SQLite contexts' `DatabaseError`: opaque on the
 * wire, full diagnostic chain preserved server-side via `tracing::error!`
 * (KEY-014 — the secret never appears in a variant or a log).
 */
export type ConnectionError = 
/**
 * The supplied key is blank or whitespace-only (KEY-010/021).
 */
{ code: "EmptyKey" } | 
/**
 * An infrastructure failure occurred against a storage tier (OS keychain /
 * session memory / plaintext file). Opaque on the wire — carries no secret
 * payload (KEY-014). The diagnostic chain is preserved via `tracing::error!`.
 */
{ code: "KeyStoreError" }
/**
 * Parameters for correcting an existing transaction.
 * `account_id` and `asset_id` are immutable — taken from the existing transaction.
 */
export type CorrectTransactionDTO = { 
/**
 * Corrected transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Corrected quantity in micro-units.
 */
quantity: number; 
/**
 * Corrected unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Corrected exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Corrected fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Parameters for creating a new account.
 */
export type CreateAccountDTO = { 
/**
 * Display name.
 */
name: string; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * Update frequency.
 */
update_frequency: UpdateFrequency }
/**
 * Parameters for creating a new asset.
 */
export type CreateAssetDTO = { 
/**
 * Display name.
 */
name: string; 
/**
 * Ticker / user-defined reference (mandatory — R1).
 */
reference: string; 
/**
 * Optional ISIN (ISO 6166, 12 chars). Validated + normalized by the domain
 * when present (AST-023, WEB-016).
 */
isin: string | null; 
/**
 * Classification type.
 */
class: AssetClass; 
/**
 * ISO currency code.
 */
currency: string; 
/**
 * 1-5 risk score.
 */
risk_level: number; 
/**
 * ID of the primary category.
 */
category_id: string; 
/**
 * Optional canonical trading venue (AST-021).
 */
exchange: Exchange | null }
/**
 * Single flat error enum for the `currency` bounded context (gold error model).
 * 
 * Every failure the BC can raise — validation, lookup, and infrastructure —
 * lives in this one type. `#[serde(tag = "code")]` makes each variant
 * serialize as `{ "code": "VariantName", ...payload }` on the wire.
 */
export type CurrencyError = 
/**
 * The rate value is zero or negative (FXR-021).
 */
{ code: "NotPositive" } | 
/**
 * The rate value is not a finite floating-point number (FXR-021). Raised
 * only at the IPC boundary by `api::rate_f64_to_micros`, before the `f64`
 * is converted to the i64 micros the domain factory accepts.
 */
{ code: "NonFinite" } | 
/**
 * The supplied date is in the future (FXR-022).
 */
{ code: "DateInFuture" } | 
/**
 * The supplied date string is not parseable as ISO 8601 `YYYY-MM-DD` (FXR-022).
 */
{ code: "InvalidDateFormat"; date: string } | 
/**
 * The supplied currency code is not a recognised ISO 4217 code (FXR-023).
 */
{ code: "InvalidCurrency"; currency: string } | 
/**
 * Both sides of a pair are the same currency — the identity rate is
 * implicit and is never stored (FXR-011/023).
 */
{ code: "IdentityPair" } | 
/**
 * No rate exists for the given pair on the given date (FXR-052/053).
 */
{ code: "RateNotFound"; from_currency: string; to_currency: string; date: string } | 
/**
 * An infrastructure / database failure occurred. The full diagnostic is
 * preserved server-side via `tracing::error!`; the wire surface carries
 * no hint.
 */
{ code: "DatabaseError" }
/**
 * A directed currency pair the system follows for valuation (FXR-013/014).
 * `(from_currency, to_currency)` is unique; the two currencies must differ (FXR-011).
 */
export type CurrencyPair = { 
/**
 * ISO 4217 source currency (e.g. `"USD"`).
 */
from_currency: string; 
/**
 * ISO 4217 target currency (e.g. `"EUR"`).
 */
to_currency: string }
/**
 * Row returned by `get_currency_pairs` (FXR-051): a pair enriched with its
 * most-recent rate (per FXR-035). The `latest_*` fields are `None` when no
 * rate has been recorded for the pair yet.
 */
export type CurrencyPairSummary = { 
/**
 * ISO 4217 source currency.
 */
from_currency: string; 
/**
 * ISO 4217 target currency.
 */
to_currency: string; 
/**
 * Micros of the most-recent rate; `None` when no rate has been recorded.
 */
latest_rate: number | null; 
/**
 * ISO date of the most-recent rate; `None` when `latest_rate` is `None`.
 */
latest_rate_date: string | null; 
/**
 * Provenance of the most-recent rate; `None` when `latest_rate` is `None`.
 */
latest_rate_source: CurrencyRateSource | null }
/**
 * A dated rate observation for a directed currency pair (FXR entity).
 * Unique by `(from_currency, to_currency, date)`.
 */
export type CurrencyRate = { 
/**
 * ISO 4217 source currency.
 */
from_currency: string; 
/**
 * ISO 4217 target currency.
 */
to_currency: string; 
/**
 * ISO 8601 date `YYYY-MM-DD` of this observation.
 */
date: string; 
/**
 * Units of `to_currency` per one unit of `from_currency`, as i64 micros (ADR-001, FXR-010).
 */
rate: number; 
/**
 * Provenance of this rate (FXR-100).
 */
source: CurrencyRateSource }
/**
 * Provenance qualifier for a CurrencyRate record (FXR-100).
 */
export type CurrencyRateSource = 
/**
 * User-driven write: manual entry or edit (FXR-101).
 */
"Manual" | 
/**
 * Auto-fetched from the Frankfurter provider (FXR-102).
 */
"Frankfurter" | 
/**
 * Auto-fetched from the ECB XML feed fallback (FXR-102).
 */
"Ecb"
/**
 * Application-layer rejection specific to the `delete_asset` use case —
 * the cross-BC transaction-history check performed by the orchestrator
 * before delegating to `AssetService::delete_asset`.
 * 
 * Per the rejection-layer rule (`docs/ddd-reference.md` § Errors): this
 * rejection is born at the orchestrator (it queries the account service and
 * decides whether to proceed), not by an aggregate method on its own loaded
 * state — application-class.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape through the
 * `DeleteAssetError` untagged composite.
 */
export type DeleteAssetApplicationError = 
/**
 * At least one transaction references this asset; deletion would break history.
 */
{ code: "ExistingTransactions" }
/**
 * Use-case composite for the **delete asset** failure surface — the single
 * command `delete_asset` and its full chain of rejections.
 * 
 * Replaces the anyhow-era `DeleteAssetCommandError` boundary type. This IS
 * the FE-facing contract for the `delete_asset` Tauri command — each leaf
 * already serializes with `#[serde(tag = "code")]`, and `#[serde(untagged)]`
 * here flattens them into a single FE-visible union.
 * 
 * Each leaf lives in its rightful layer:
 * - `AssetCrudError` — asset BC composite (`asset/application/`), carries
 * `AssetApplicationError::NotFound` and
 * `AssetDomainError::CashAssetNotEditable` propagated verbatim per the
 * composition-over-redefinition rule.
 * - `AccountApplicationError` — account BC (`account/application/`), surfaces
 * `DatabaseError` from the cross-BC transaction-history check.
 * - `DeleteAssetApplicationError` — use-case-owned (this file), raises
 * `ExistingTransactions` from the orchestrator.
 */
export type DeleteAssetError = 
/**
 * Asset BC rejection (`NotFound`, `CashAssetNotEditable`, propagated
 * `DatabaseError`).
 */
AssetCrudError | 
/**
 * Account BC rejection (`DatabaseError` from the cross-BC
 * transaction-history check).
 */
AccountApplicationError | 
/**
 * Use-case orchestration rejection (`ExistingTransactions`).
 */
DeleteAssetApplicationError
/**
 * Parameters for recording a cash deposit (CSH-020).
 */
export type DepositDTO = { 
/**
 * Account receiving the cash.
 */
account_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Deposited amount in account currency (micro-units); strictly positive (CSH-021).
 */
amount_micros: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Application-layer rejections specific to the `record_dividend` use case —
 * cross-BC asset and holding checks performed by the orchestrator before
 * delegating to `AccountService::record_dividend`.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape.
 */
export type DividendApplicationError = 
/**
 * No asset exists with the requested ID (DIV-011).
 */
{ code: "AssetNotFound" } | 
/**
 * The asset is not currently held (quantity = 0 or no holding) (DIV-011).
 */
{ code: "AssetNotHeld" } | 
/**
 * Target asset is a system Cash Asset — dividends must be on non-cash
 * holdings (DIV-011).
 */
{ code: "DividendOnCashAsset" }
/**
 * Parameters for recording a cash dividend attributed to a held asset (DIV-020).
 */
export type DividendDTO = { 
/**
 * Account receiving the dividend.
 */
account_id: string; 
/**
 * The paying asset — must be actively held (quantity > 0) and not a Cash Asset (DIV-011).
 */
asset_id: string; 
/**
 * Business date the dividend was received (YYYY-MM-DD, DIV-021).
 */
date: string; 
/**
 * Net dividend in the asset's native currency (micro-units, strictly positive, DIV-021).
 */
amount_micros: number; 
/**
 * Asset→account conversion rate (micro-units, strictly positive; 1_000_000 when currencies match, DIV-022).
 */
exchange_rate: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Use-case composite for the **record dividend** failure surface.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer, raises `AccountNotFound`
 * and `DatabaseError`.
 * - `DividendApplicationError` — use-case-owned (this file), raises the
 * cross-BC asset/holding checks.
 * - `TransactionDomainError` — domain layer, raises date / amount / rate
 * validation errors.
 */
export type DividendError = 
/**
 * Account-side rejection (`AccountNotFound`, `DatabaseError`).
 */
AccountApplicationError | 
/**
 * Use-case-layer rejection (cross-BC asset checks).
 */
DividendApplicationError | 
/**
 * Transaction-factory / domain validation rejection.
 */
TransactionDomainError
/**
 * All possible side-effect events that can be published across the application.
 * Each variant represents a specific business event that features may need to react to.
 */
export type Event = 
/**
 * Health check event for testing/monitoring
 */
{ type: "Health" } | 
/**
 * An asset was created, updated, or deleted
 */
{ type: "AssetUpdated" } | 
/**
 * An account was created, updated, or deleted
 */
{ type: "AccountUpdated" } | 
/**
 * A category was created, updated, or deleted
 */
{ type: "CategoryUpdated" } | 
/**
 * A transaction was created, updated, or deleted (position data changed)
 */
{ type: "TransactionUpdated" } | 
/**
 * A market price was recorded or updated for an asset (MKT-026)
 */
{ type: "AssetPriceUpdated" } | 
/**
 * A price-fetch task finished: `ok` assets were updated, `skipped` were not
 * (no data or fetch failure). Carries counts so the frontend can summarize
 * the outcome (MKT-119). Distinct from the per-asset `AssetPriceUpdated`.
 */
{ type: "AssetPriceFetchCompleted"; ok: number; skipped: number } | 
/**
 * A currency rate was recorded, updated, or deleted (FXR-026/052/053/074).
 */
{ type: "CurrencyRateUpdated" }
/**
 * A canonical trading venue identified by its ISO 10383 MIC code.
 */
export type Exchange = { 
/**
 * ISO 10383 Market Identifier Code (e.g. "XPAR", "XNAS").
 */
code: string; 
/**
 * Human-readable display name (e.g. "Euronext Paris").
 */
label: string }
/**
 * Wire-facing error composite for `fetch_account_asset_prices` (MKT-113, MKT-111, MKT-132).
 * 
 * See `FetchAllAssetPricesError` for the shared shape rationale.
 */
export type FetchAccountAssetPricesError = 
/**
 * Propagates asset-BC failures (e.g. `DatabaseError`) via `?`.
 */
AssetError | 
/**
 * Propagates account-BC failures (`AccountNotFound`, `DatabaseError`) via `?`.
 */
AccountApplicationError | 
/**
 * Use-case-specific failures (`FetchAlreadyRunning`, `NoFetchableHoldings`, `UnknownError`).
 */
FetchPriceTask
/**
 * Wire-facing error composite for `fetch_all_asset_prices` (MKT-113, MKT-111, MKT-122).
 * 
 * `#[serde(untagged)]` lets every arm surface its inner `{ "code": "..." }` payload
 * directly on the wire. Each arm carries a tagged inner type (BC enum or
 * `FetchPriceTask`) so the discriminator survives the untagging.
 */
export type FetchAllAssetPricesError = 
/**
 * Propagates asset-BC failures (e.g. `DatabaseError`) via `?`.
 */
AssetError | 
/**
 * Propagates account-BC failures (`AccountNotFound`, `DatabaseError`) via `?`.
 */
AccountApplicationError | 
/**
 * Use-case-specific failures (`FetchAlreadyRunning`, `NoFetchableHoldings`, `UnknownError`).
 */
FetchPriceTask
/**
 * Use-case-specific outcomes for the asset-price fetch tasks shared by
 * `FetchAllAssetPricesError` and `FetchAccountAssetPricesError`.
 * 
 * Carried inside each composite as a single `Failure(#[from] FetchPriceTask)` arm.
 * `#[serde(tag = "code")]` gives every variant a `{ "code": "..." }` payload so the
 * surrounding `#[serde(untagged)]` composite emits a flat, narrowable shape on the
 * wire.
 */
export type FetchPriceTask = 
/**
 * A fetch task is already in progress (MKT-113).
 */
{ code: "FetchAlreadyRunning" } | 
/**
 * No active holdings with a derivable provider symbol found in scope (MKT-111).
 */
{ code: "NoFetchableHoldings" } | 
/**
 * Catch-all for unexpected runtime failures not attributable to a specific BC.
 */
{ code: "UnknownError" }
/**
 * Application-layer rejections specific to the `record_free_shares` use case —
 * cross-BC asset and holding checks performed by the orchestrator before
 * delegating to `AccountService::record_free_shares`.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape.
 */
export type FreeSharesApplicationError = 
/**
 * No asset exists with the requested ID (FSD-011).
 */
{ code: "AssetNotFound" } | 
/**
 * The asset is not currently held (quantity = 0 or no holding) (FSD-011).
 */
{ code: "AssetNotHeld" } | 
/**
 * Target asset is a system Cash Asset — free shares must be on non-cash
 * holdings (FSD-011).
 */
{ code: "FreeSharesOnCashAsset" }
/**
 * Parameters for recording a zero-cost free-share distribution from a held
 * distributing asset (FSD-020). No amount, no unit price, no exchange rate,
 * no fees — no money changes hands.
 */
export type FreeSharesDTO = { 
/**
 * Account whose holding receives the free shares.
 */
account_id: string; 
/**
 * The distributing asset — must be actively held (quantity > 0) and not a Cash Asset (FSD-011).
 */
asset_id: string; 
/**
 * Business date the shares were received (YYYY-MM-DD, FSD-021).
 */
date: string; 
/**
 * Number of free shares received (micro-units, strictly positive, FSD-021).
 */
quantity: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Use-case composite for the **record free shares** failure surface.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer, raises `AccountNotFound`
 * and `DatabaseError`.
 * - `FreeSharesApplicationError` — use-case-owned (this file), raises the
 * cross-BC asset/holding checks.
 * - `TransactionDomainError` — domain layer, raises date / quantity
 * validation errors.
 */
export type FreeSharesError = 
/**
 * Account-side rejection (`AccountNotFound`, `DatabaseError`).
 */
AccountApplicationError | 
/**
 * Use-case-layer rejection (cross-BC asset checks).
 */
FreeSharesApplicationError | 
/**
 * Transaction-factory / domain validation rejection.
 */
TransactionDomainError
/**
 * Current state of a financial position: an asset held within an account (ADR-002).
 * All financial fields are stored as i64 micro-units (ADR-001).
 */
export type Holding = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * The account holding the asset.
 */
account_id: string; 
/**
 * The financial asset held.
 */
asset_id: string; 
/**
 * Current number of units held (micro-units: value × 10^6).
 */
quantity: number; 
/**
 * Volume-weighted average purchase price in account currency (micro-units).
 */
average_price: number; 
/**
 * Cumulative realized P&L from all sell transactions (micro-units, ACD-045).
 */
total_realized_pnl: number; 
/**
 * ISO date of the most recent sell transaction, if any (ACD-043).
 */
last_sold_date: string | null }
/**
 * Enriched view of a single active holding (quantity > 0) with asset metadata (ACD-020).
 */
export type HoldingDetail = { 
/**
 * ID of the held asset.
 */
asset_id: string; 
/**
 * Display name of the asset.
 */
asset_name: string; 
/**
 * Ticker or user-defined reference.
 */
asset_reference: string; 
/**
 * Current units held (i64 micro-units, ADR-001).
 */
quantity: number; 
/**
 * VWAP purchase price in account currency (i64 micro-units, ADR-001).
 */
average_price: number; 
/**
 * Total cost of position: quantity × average_price / MICRO (i64 micro-units, ACD-023).
 */
cost_basis: number; 
/**
 * Sum of realized P&L from all Sell transactions for this asset (i64 micro-units, SEL-042).
 */
realized_pnl: number; 
/**
 * ISO 4217 currency code of the asset's native currency (MKT-023).
 */
asset_currency: string; 
/**
 * Most recently dated price for this asset in asset currency (i64 micros). None if no price recorded (MKT-031).
 */
current_price: number | null; 
/**
 * ISO date string of the price observation. None when current_price is None (MKT-031).
 */
current_price_date: string | null; 
/**
 * Provenance of `current_price`. None when current_price is None (MKT-142).
 */
current_price_source: AssetPriceSource | null; 
/**
 * Unrealized gain/loss in account currency (i64 micros). None when no price exists, or
 * when a foreign holding has no usable rate (MKT-033/034, FXR-031/034).
 * 0 (not None) when current price equals average price (MKT-033).
 */
unrealized_pnl: number | null; 
/**
 * Performance percentage as i64 micros (5.25% = 5_250_000). None when unrealized_pnl is None or cost_basis = 0 (MKT-035).
 * 0 (not None) when unrealized_pnl is 0 (MKT-035).
 */
performance_pct: number | null; 
/**
 * Sum of dividend cash credited for this (account, asset), in account currency (i64 micros).
 * 0 when no dividends recorded; always computable (DIV-070).
 */
dividends_received: number; 
/**
 * Dividend-inclusive total return: (unrealized_pnl + dividends_received) × 100 / cost_basis.
 * None under the same conditions as performance_pct (DIV-071).
 */
total_return_pct: number | null; 
/**
 * ISO date of the FX rate used to value a foreign holding in the account
 * currency (FXR-090). `None` for a same-currency holding (no conversion),
 * a foreign holding with no usable rate, or cash — i.e. present only when a
 * converted value backed by a real rate is shown.
 */
fx_rate_date: string | null }
/**
 * Service-layer composite for the **holding-transaction** failure surface —
 * every operation that mutates an Account's holdings ledger:
 * `record_deposit`, `record_withdrawal`, `buy_holding`, `sell_holding`,
 * `correct_transaction`, `cancel_transaction`.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer (this module)
 * - `AccountOperationError` — domain layer (`account/domain/`)
 * - `TransactionDomainError` — domain layer (`account/domain/`)
 */
export type HoldingTransactionError = 
/**
 * Application-layer rejection (`AccountNotFound`, `DatabaseError`).
 */
AccountApplicationError | 
/**
 * Aggregate-level domain rejection (e.g. `InsufficientCash` from
 * `Account::apply_withdrawal`, `Oversell` from `sell_holding`).
 */
AccountOperationError | 
/**
 * Transaction-factory validation rejection (invalid date, negative
 * quantity, `AmountNotPositive` from cash factories, etc.).
 */
TransactionDomainError
/**
 * Explicit lookup path selector passed by the frontend (WEB-014).
 * 
 * `Isin` routes the query through `/v3/mapping` after ISO 6166 format
 * validation (WEB-016). `Keyword` routes through `/v3/search` with
 * diacritics normalization (WEB-015).
 */
export type LookupMode = 
/**
 * ISIN path: validate format (WEB-016) then call `/v3/mapping`.
 */
"Isin" | 
/**
 * Keyword path: normalize diacritics (WEB-015) then call `/v3/search`.
 */
"Keyword"
/**
 * Application-layer rejections specific to the `open_holding` use case —
 * cross-BC asset checks performed by the orchestrator before delegating to
 * `AccountService::open_holding`.
 * 
 * Tagged with `#[serde(tag = "code")]` so it serializes verbatim across the
 * Tauri boundary into a flat `{ code: "..." }` shape.
 */
export type OpenHoldingApplicationError = 
/**
 * No asset exists with the requested ID (TRX-056).
 */
{ code: "AssetNotFound" } | 
/**
 * Target asset is archived — cannot open a holding (TRX-050).
 * The orchestrator does not auto-unarchive; the caller must unarchive
 * explicitly through the asset BC first.
 */
{ code: "ArchivedAsset" } | 
/**
 * Target asset is a system Cash Asset (CSH-061). Initial cash should be
 * recorded via `record_deposit`, which goes through the cash-recording
 * path and lazy-creates the Cash Holding.
 */
{ code: "OpeningBalanceOnCashAsset" }
/**
 * Parameters for recording an opening balance for an asset in an account (TRX-042).
 */
export type OpenHoldingDTO = { 
/**
 * Account where the opening balance is recorded.
 */
account_id: string; 
/**
 * Financial asset being seeded.
 */
asset_id: string; 
/**
 * Date of the opening balance (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units; strictly positive (TRX-044).
 */
quantity: number; 
/**
 * Total cost paid in account currency (micro-units); strictly positive (TRX-045).
 */
total_cost: number }
/**
 * Use-case composite for the **open holding** failure surface — the single
 * command `open_holding` (TRX-042) and its full chain of rejections.
 * 
 * Each leaf lives in its rightful layer:
 * - `AccountApplicationError` — application layer (`account/application/`),
 * raises `AccountNotFound { account_id }` and `DatabaseError` from
 * account-side service operations. Asset-side `DatabaseError` from the
 * cross-BC `get_asset_by_id` lookup is also tunnelled through this leaf
 * (the orchestrator translates at the call site) so the FE wire surface
 * carries a single `{ code: "DatabaseError" }` shape.
 * - `OpenHoldingApplicationError` — use-case-owned (this file), raises the
 * 3 cross-BC rejections (`AssetNotFound`, `ArchivedAsset`,
 * `OpeningBalanceOnCashAsset`).
 * - `OpeningBalanceDomainError` — domain layer (`account/domain/`), raises
 * `InvalidTotalCost` from `Account::open_holding` on its own input.
 * - `TransactionDomainError` — domain layer (`account/domain/`), raises
 * the date / quantity invariants enforced by `Transaction::new`.
 */
export type OpenHoldingError = 
/**
 * Account-side rejection (`AccountNotFound`, `DatabaseError`).
 */
AccountApplicationError | 
/**
 * Use-case-layer rejection (cross-BC asset checks).
 */
OpenHoldingApplicationError | 
/**
 * Aggregate-level domain rejection (`InvalidTotalCost`).
 */
OpeningBalanceDomainError | 
/**
 * Transaction-factory validation rejection (invalid date, negative
 * quantity, etc. — subset of variants reachable from `open_holding`).
 */
TransactionDomainError
/**
 * Aggregate-level domain rejection raised by `Account::open_holding` on its
 * own input — currently only the `total_cost > 0` invariant (TRX-045).
 */
export type OpeningBalanceDomainError = 
/**
 * total_cost was zero or negative (TRX-045).
 */
{ code: "InvalidTotalCost" }
/**
 * Net-of-flows performance figures for one period (PRF-031, PRF-032).
 */
export type PerformanceMetric = { 
/**
 * Net-of-flows gain in account-currency micros (PRF-031).
 */
gain: number; 
/**
 * Simple Dietz percentage as micro-percent (8.00% = 8_000_000).
 * None when the Dietz denominator is 0 (PRF-032).
 */
pct: number | null }
/**
 * One calendar period row (PRF-020, PRF-040).
 */
export type PerformancePeriod = { 
/**
 * Calendar year of this row.
 */
year: number; 
/**
 * Some(1..=12) for month rows; None for year rows (PRF-011).
 */
month: number | null; 
/**
 * Global Value at period end in account-currency micros (PRF-020).
 */
end_value: number; 
/**
 * Performance vs the preceding period of the same granularity (PRF-033).
 * None when no preceding period exists (PRF-042).
 */
period_over_period: PerformanceMetric | null; 
/**
 * Performance from the start of the calendar year to this period end (PRF-034).
 * None for year rows (PRF-037) or when the year-start baseline is absent (PRF-034).
 */
year_to_date: PerformanceMetric | null; 
/**
 * Performance from inception to this period end, vs net invested (PRF-035).
 */
since_inception: PerformanceMetric | null }
/**
 * Which external provider a connection authenticates (KEY-031). Extensible:
 * Finnhub / OpenFIGI arrive as further variants in later slices.
 */
export type Provider = 
/**
 * Stooq daily-close price provider (ADR-015).
 */
"Stooq"
/**
 * Non-secret state of one provider's connection, surfaced to the UI (KEY-016).
 */
export type ProviderConnection = { 
/**
 * Which provider this connection authenticates.
 */
provider: Provider; 
/**
 * Whether a key is stored (KEY-016); the value is never exposed (KEY-018).
 */
has_key: boolean; 
/**
 * Where the key lives (KEY-015); `None` when `has_key` is false.
 */
active_tier: StorageTier | null }
/**
 * Result of probing a provider with a candidate key (KEY-023).
 */
export type ProviderKeyTestOutcome = 
/**
 * The provider accepted the key.
 */
"Accepted" | 
/**
 * The provider was reachable but rejected the key.
 */
"Rejected" | 
/**
 * The provider could not be contacted (network failure).
 */
"Unreachable"
/**
 * Arguments for `remove_provider_key` (KEY-013).
 */
export type RemoveProviderKeyArgs = { 
/**
 * Which provider's key to clear.
 */
provider: Provider }
/**
 * Arguments for `save_provider_key` (KEY-010/012).
 * 
 * `Debug` is implemented manually to redact the secret `key` (KEY-014): the
 * derived form would render it verbatim in any `{:?}`.
 */
export type SaveProviderKeyArgs = { 
/**
 * Which provider the key authenticates.
 */
provider: Provider; 
/**
 * The pasted secret; write-only from the UI's perspective (KEY-018).
 */
key: string; 
/**
 * Tier-3 opt-in (KEY-012); `false` keeps the key off disk on a keyring-less host.
 */
allow_plaintext: boolean }
/**
 * Parameters for recording a sale of an asset from an account.
 */
export type SellHoldingDTO = { 
/**
 * Account where the sale is recorded.
 */
account_id: string; 
/**
 * Financial asset being sold.
 */
asset_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units.
 */
quantity: number; 
/**
 * Unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * Where a stored key currently lives, per the ADR-011 ladder (KEY-011, KEY-015).
 */
export type StorageTier = 
/**
 * Tier 1 — default, persists, OS-encrypted.
 */
"OsKeychain" | 
/**
 * Tier 2 — fallback, RAM-only, cleared on exit (KEY-017).
 */
"SessionMemory" | 
/**
 * Tier 3 — explicit opt-in only (KEY-012).
 */
"PlaintextFile"
/**
 * Arguments for `test_provider_key` (KEY-021). `Debug` redacts the secret `key`
 * (KEY-014).
 */
export type TestProviderKeyArgs = { 
/**
 * Which provider to probe.
 */
provider: Provider; 
/**
 * The candidate key to test (not necessarily the stored one).
 */
key: string }
/**
 * A single financial event affecting an asset's quantity and cost basis within an account.
 * All financial fields are stored as i64 micro-units (ADR-001, TRX-024).
 */
export type Transaction = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * The account where the transaction occurred.
 */
account_id: string; 
/**
 * The financial asset involved.
 */
asset_id: string; 
/**
 * Type of transaction: Purchase, Sell, or OpeningBalance.
 */
transaction_type: TransactionType; 
/**
 * Date when the transaction was executed (ISO 8601, "YYYY-MM-DD").
 */
date: string; 
/**
 * Number of units traded (micro-units: value × 10^6). Must be > 0.
 */
quantity: number; 
/**
 * Price per unit in asset's native currency (micro-units). Can be 0 (gifted assets).
 */
unit_price: number; 
/**
 * Conversion rate from asset currency to account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Transaction fees in account currency (micro-units).
 */
fees: number; 
/**
 * Total cost (Purchase) or proceeds (Sell) in account currency (micro-units). Must be > 0.
 */
total_amount: number; 
/**
 * Optional user comment.
 */
note: string | null; 
/**
 * Realized P&L for Sell transactions (micro-units, SEL-024). NULL for Purchase.
 */
realized_pnl: number | null; 
/**
 * ISO 8601 timestamp of record creation — used for same-date tie-breaking (SEL-024).
 */
created_at: string }
/**
 * Typed errors for transaction domain validation (TRX-020).
 * 
 * Derives `Serialize + specta::Type + #[serde(tag = "code")]` so it can be exposed
 * at the Tauri boundary verbatim — boundary error types compose this enum via
 * untagged unions instead of redefining its variants (PR #5 review feedback).
 */
export type TransactionDomainError = 
/**
 * Date string could not be parsed as YYYY-MM-DD.
 */
{ code: "InvalidDate" } | 
/**
 * Transaction date is in the future.
 */
{ code: "DateInFuture" } | 
/**
 * Transaction date is before 1900-01-01.
 */
{ code: "DateTooOld" } | 
/**
 * Quantity is zero or negative.
 */
{ code: "QuantityNotPositive" } | 
/**
 * Cash deposit/withdrawal amount was zero or negative (CSH-021/CSH-031).
 * Cash-specific framing of the same TRX-020 constraint that surfaces as
 * `QuantityNotPositive` for non-cash transactions; raised by the cash
 * factories (`Transaction::new_deposit` / `new_withdrawal`) BEFORE the
 * generic check, so the FE sees the cash-specific error code.
 */
{ code: "AmountNotPositive" } | 
/**
 * Unit price is negative.
 */
{ code: "UnitPriceNegative" } | 
/**
 * Fees amount is negative.
 */
{ code: "FeesNegative" } | 
/**
 * Exchange rate is zero or negative.
 */
{ code: "ExchangeRateNotPositive" } | 
/**
 * Total amount is zero or negative.
 */
{ code: "TotalAmountNotPositive" }
/**
 * Type of financial transaction.
 */
export type TransactionType = 
/**
 * A purchase (acquisition) of an asset.
 */
"Purchase" | 
/**
 * A sale of a previously purchased asset.
 */
"Sell" | 
/**
 * Seeds a holding directly from a known quantity and total cost, without full transaction history (TRX-042).
 */
"OpeningBalance" | 
/**
 * A cash inflow from outside the application's tracked world (CSH-022).
 */
"Deposit" | 
/**
 * A cash outflow to outside the application's tracked world (CSH-032).
 */
"Withdrawal" | 
/**
 * A cash dividend paid by a held asset; credited to the Cash Holding (DIV-023).
 */
"Dividend" | 
/**
 * Shares of a held asset received at no cost; quantity rises, cost basis unchanged (FSD-022).
 */
"FreeShares"
/**
 * Parameters for updating an existing account.
 */
export type UpdateAccountDTO = { 
/**
 * Target account ID.
 */
id: string; 
/**
 * New display name.
 */
name: string; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * New update frequency.
 */
update_frequency: UpdateFrequency }
/**
 * Parameters for updating an existing asset.
 */
export type UpdateAssetDTO = { 
/**
 * Target asset ID.
 */
asset_id: string; 
/**
 * New display name.
 */
name: string; 
/**
 * New reference (mandatory — R1).
 */
reference: string; 
/**
 * New optional ISIN (AST-023). `None` clears the field.
 */
isin: string | null; 
/**
 * New classification.
 */
class: AssetClass; 
/**
 * New currency.
 */
currency: string; 
/**
 * New risk level.
 */
risk_level: number; 
/**
 * New category link.
 */
category_id: string; 
/**
 * New optional canonical trading venue (AST-021 / AST-022).
 */
exchange: Exchange | null }
/**
 * Defines how often an account's data should be updated.
 */
export type UpdateFrequency = 
/**
 * Automatic updates (e.g. via API)
 */
"Automatic" | 
/**
 * Manual update daily
 */
"ManualDay" | 
/**
 * Manual update weekly
 */
"ManualWeek" | 
/**
 * Manual update monthly
 */
"ManualMonth" | 
/**
 * Manual update yearly
 */
"ManualYear"
/**
 * Information about an available application update.
 */
export type UpdateInfo = { 
/**
 * Semantic version string of the available update (e.g. "1.2.3").
 */
version: string }
/**
 * Application-layer errors raised by the asset web-lookup use case (WEB-025).
 */
export type WebLookupApplicationError = 
/**
 * OpenFIGI returned HTTP 429 Too Many Requests — transient, recoverable
 * after a short wait. Surfaced distinctly so the frontend can render
 * retry-after-wait copy (WEB-033).
 */
{ code: "RateLimited" } | 
/**
 * Network unreachable, connection timeout, or any non-2xx HTTP status
 * other than 429.
 */
{ code: "NetworkError" } | 
/**
 * The query was submitted on the ISIN path (`LookupMode::Isin`) but does
 * not satisfy the ISO 6166 format rules: wrong length, invalid charset, or
 * failing Luhn-mod-10 check digit (WEB-016, WEB-025).
 * 
 * Wire shape: `{ "code": "InvalidIsinFormat" }` — no payload; the FE
 * renders a single static copy string.
 */
{ code: "InvalidIsinFormat" }
/**
 * Parameters for recording a cash withdrawal (CSH-030).
 */
export type WithdrawalDTO = { 
/**
 * Account from which to withdraw cash.
 */
account_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Withdrawn amount in account currency (micro-units); strictly positive (CSH-031).
 */
amount_micros: number; 
/**
 * Optional user note.
 */
note: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
