// @ts-nocheck
/* eslint-disable */
// Generated by Specta - do not edit manually

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Fetches all active (non-archived) assets.
 */
async getAssets() : Promise<Result<Asset[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches all assets including archived ones.
 */
async getAssetsWithArchived() : Promise<Result<Asset[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_assets_with_archived") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new asset.
 */
async addAsset(dto: CreateAssetDTO) : Promise<Result<Asset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_asset", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing asset.
 */
async updateAsset(dto: UpdateAssetDTO) : Promise<Result<Asset, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_asset", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Archives an asset (reversible soft-archive — R6).
 */
async archiveAsset(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Unarchives an asset (R18).
 */
async unarchiveAsset(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unarchive_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an asset.
 */
async deleteAsset(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_asset", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Fetches all active categories.
 */
async getCategories() : Promise<Result<AssetCategory[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_categories") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new category.
 */
async addCategory(label: string) : Promise<Result<AssetCategory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_category", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing category.
 */
async updateCategory(id: string, label: string) : Promise<Result<AssetCategory, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_category", { id, label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a category.
 */
async deleteCategory(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_category", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all accounts.
 */
async getAccounts() : Promise<Result<Account[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_accounts") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Adds a new account.
 */
async addAccount(dto: CreateAccountDTO) : Promise<Result<Account, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_account", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing account.
 */
async updateAccount(dto: UpdateAccountDTO) : Promise<Result<Account, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_account", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes an account.
 */
async deleteAccount(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_account", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri command allowing the frontend to emit structured log entries
 * into the backend tracing system (visible in app logs and collect-logs output).
 */
async logFrontend(level: string, message: string) : Promise<void> {
    await TAURI_INVOKE("log_frontend", { level, message });
},
/**
 * Checks whether a new application version is available (R1, R25).
 * 
 * Returns `None` if the application is up to date or if the check fails due
 * to network or server errors (R21). Emits `"update:available"` on the app
 * handle if an update is found.
 */
async checkForUpdate() : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Starts downloading the available update in the background (R6).
 * 
 * Returns immediately — the download runs as a detached async task.
 * Progress is reported via `"update:progress"` events (R8).
 * On success, emits `"update:complete"` (R11).
 * On failure, emits `"update:error"` (R23).
 * Concurrent download requests are silently ignored (R10).
 */
async downloadUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Installs the downloaded update and restarts the application (R13).
 * 
 * Must be called after `download_update` has completed successfully.
 * Returns an error if no downloaded update is available.
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Creates a new purchase transaction and updates the Holding atomically (TRX-027).
 */
async addTransaction(dto: CreateTransactionDTO) : Promise<Result<Transaction, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_transaction", { dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Updates an existing transaction and recalculates the affected Holding(s) (TRX-031, TRX-032).
 */
async updateTransaction(id: string, dto: CreateTransactionDTO) : Promise<Result<Transaction, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_transaction", { id, dto }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Deletes a transaction and recalculates (or removes) the associated Holding (TRX-034).
 */
async deleteTransaction(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_transaction", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Retrieves all transactions for an account/asset pair.
 */
async getTransactions(accountId: string, assetId: string) : Promise<Result<Transaction[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_transactions", { accountId, assetId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the distinct asset IDs that have transactions for the given account (TXL-013).
 */
async getAssetIdsForAccount(accountId: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_asset_ids_for_account", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the full account details view for the given account (ACD-012 to ACD-041).
 */
async getAccountDetails(accountId: string) : Promise<Result<AccountDetailsResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_account_details", { accountId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/


export const events = __makeEvents__<{
event: Event
}>({
event: "event"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * Represents a financial account.
 */
export type Account = { 
/**
 * Unique identifier (uuid).
 */
id: string; 
/**
 * User defined name.
 */
name: string; 
/**
 * How often this account is updated.
 */
update_frequency: UpdateFrequency }
/**
 * Top-level response for the get_account_details command (ACD spec).
 */
export type AccountDetailsResponse = { 
/**
 * Display name of the account (ACD-032).
 */
account_name: string; 
/**
 * Active holdings sorted by asset_name ascending (ACD-020, ACD-033).
 */
holdings: HoldingDetail[]; 
/**
 * Total holding count regardless of quantity (ACD-034).
 */
total_holding_count: number; 
/**
 * Sum of cost_basis across all active holdings, 0 if none (ACD-031).
 */
total_cost_basis: number }
/**
 * A financial instrument or resource held by a user.
 */
export type Asset = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * Display name.
 */
name: string; 
/**
 * Asset classification.
 */
class: AssetClass; 
/**
 * Category link.
 */
category: AssetCategory; 
/**
 * ISO 4217 currency code.
 */
currency: string; 
/**
 * Risk score from 1 to 5.
 */
risk_level: number; 
/**
 * Identifier like ticker or ISIN.
 */
reference: string; 
/**
 * Whether the asset is archived (soft-archived, reversible).
 */
is_archived: boolean }
/**
 * A user-defined grouping for assets.
 */
export type AssetCategory = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * Display name.
 */
name: string }
/**
 * Represents the classification of an asset.
 */
export type AssetClass = 
/**
 * Real estate properties or REITs.
 */
"RealEstate" | 
/**
 * Fiat currency or highly liquid equivalents.
 */
"Cash" | 
/**
 * Individual company equities.
 */
"Stocks" | 
/**
 * Fixed income securities.
 */
"Bonds" | 
/**
 * Exchange Traded Funds.
 */
"ETF" | 
/**
 * Managed investment funds.
 */
"MutualFunds" | 
/**
 * Cryptocurrencies or other blockchain-based assets.
 */
"DigitalAsset"
/**
 * Parameters for creating a new account.
 */
export type CreateAccountDTO = { 
/**
 * Display name.
 */
name: string; 
/**
 * Update frequency.
 */
update_frequency: UpdateFrequency }
/**
 * Parameters for creating a new asset.
 */
export type CreateAssetDTO = { 
/**
 * Display name.
 */
name: string; 
/**
 * Ticker, ISIN, or user-defined reference (mandatory — R1).
 */
reference: string; 
/**
 * Classification type.
 */
class: AssetClass; 
/**
 * ISO currency code.
 */
currency: string; 
/**
 * 1-5 risk score.
 */
risk_level: number; 
/**
 * ID of the primary category.
 */
category_id: string }
/**
 * DTO for creating or updating a transaction.
 * `total_amount` is intentionally absent — the backend computes it from the other
 * fields (TRX-026) so the frontend never sends a derived value over the wire.
 */
export type CreateTransactionDTO = { 
/**
 * Account where the transaction occurs.
 */
account_id: string; 
/**
 * Financial asset involved.
 */
asset_id: string; 
/**
 * Transaction date (YYYY-MM-DD).
 */
date: string; 
/**
 * Quantity in micro-units.
 */
quantity: number; 
/**
 * Unit price in asset currency (micro-units).
 */
unit_price: number; 
/**
 * Exchange rate asset→account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Fees in account currency (micro-units).
 */
fees: number; 
/**
 * Optional user note.
 */
note: string | null }
/**
 * All possible side-effect events that can be published across the application.
 * Each variant represents a specific business event that features may need to react to.
 */
export type Event = 
/**
 * Health check event for testing/monitoring
 */
{ type: "Health" } | 
/**
 * An asset was created, updated, or deleted
 */
{ type: "AssetUpdated" } | 
/**
 * An account was created, updated, or deleted
 */
{ type: "AccountUpdated" } | 
/**
 * A category was created, updated, or deleted
 */
{ type: "CategoryUpdated" } | 
/**
 * A transaction was created, updated, or deleted (position data changed)
 */
{ type: "TransactionUpdated" }
/**
 * Current state of a financial position: an asset held within an account (ADR-002).
 * All financial fields are stored as i64 micro-units (ADR-001).
 */
export type Holding = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * The account holding the asset.
 */
account_id: string; 
/**
 * The financial asset held.
 */
asset_id: string; 
/**
 * Current number of units held (micro-units: value × 10^6).
 */
quantity: number; 
/**
 * Volume-weighted average purchase price in account currency (micro-units).
 */
average_price: number }
/**
 * Enriched view of a single holding with asset metadata and computed cost basis (ACD spec).
 */
export type HoldingDetail = { 
/**
 * ID of the held asset.
 */
asset_id: string; 
/**
 * Display name of the asset.
 */
asset_name: string; 
/**
 * Ticker or user-defined reference.
 */
asset_reference: string; 
/**
 * Current units held (i64 micro-units, ADR-001).
 */
quantity: number; 
/**
 * VWAP purchase price in account currency (i64 micro-units, ADR-001).
 */
average_price: number; 
/**
 * Total cost of position: quantity × average_price / MICRO (i64 micro-units, ACD-023).
 */
cost_basis: number }
/**
 * A single financial event affecting an asset's quantity and cost basis within an account.
 * All financial fields are stored as i64 micro-units (ADR-001, TRX-024).
 */
export type Transaction = { 
/**
 * Unique identifier.
 */
id: string; 
/**
 * The account where the transaction occurred.
 */
account_id: string; 
/**
 * The financial asset involved.
 */
asset_id: string; 
/**
 * Type of transaction (Purchase; Sell deferred per TRX-040).
 */
transaction_type: TransactionType; 
/**
 * Date when the transaction was executed (ISO 8601, "YYYY-MM-DD").
 */
date: string; 
/**
 * Number of units acquired (micro-units: value × 10^6). Must be > 0.
 */
quantity: number; 
/**
 * Price per unit in asset's native currency (micro-units). Can be 0 (gifted assets).
 */
unit_price: number; 
/**
 * Conversion rate from asset currency to account currency (micro-units).
 */
exchange_rate: number; 
/**
 * Transaction fees in account currency (micro-units).
 */
fees: number; 
/**
 * Total cost in account currency including fees (micro-units). Must be > 0.
 */
total_amount: number; 
/**
 * Optional user comment.
 */
note: string | null }
/**
 * Type of financial transaction.
 */
export type TransactionType = 
/**
 * A purchase (acquisition) of an asset.
 */
"Purchase"
/**
 * Parameters for updating an existing account.
 */
export type UpdateAccountDTO = { 
/**
 * Target account ID.
 */
id: string; 
/**
 * New display name.
 */
name: string; 
/**
 * New update frequency.
 */
update_frequency: UpdateFrequency }
/**
 * Parameters for updating an existing asset.
 */
export type UpdateAssetDTO = { 
/**
 * Target asset ID.
 */
asset_id: string; 
/**
 * New display name.
 */
name: string; 
/**
 * New reference (mandatory — R1).
 */
reference: string; 
/**
 * New classification.
 */
class: AssetClass; 
/**
 * New currency.
 */
currency: string; 
/**
 * New risk level.
 */
risk_level: number; 
/**
 * New category link.
 */
category_id: string }
/**
 * Defines how often an account's data should be updated.
 */
export type UpdateFrequency = 
/**
 * Automatic updates (e.g. via API)
 */
"Automatic" | 
/**
 * Manual update daily
 */
"ManualDay" | 
/**
 * Manual update weekly
 */
"ManualWeek" | 
/**
 * Manual update monthly
 */
"ManualMonth" | 
/**
 * Manual update yearly
 */
"ManualYear"
/**
 * Information about an available application update.
 */
export type UpdateInfo = { 
/**
 * Semantic version string of the available update (e.g. "1.2.3").
 */
version: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
